### ISSUE TITLE
TeX-Output

### ISSUE THREAD

**Issue by rogerwalt** [strpeter/falshcards#1]
Ist fehlerhaft. Bitte die Datei

 ProjectK / Symfony / src / Falshcards / FalshcardsBundle / Resources / views / Card / export.tex.twig

anpassen, bis das TeX-Template funktioniert ;-).

**Comment by strpeter** [comment]
The problem was that the linebreaks in the documentclass got deleted. Now, I have placed them again. But deleted also the unused comments inside it in order to prevent future errors. We can place the arguments at the effective export step.
