### ISSUE TITLE
Export cards to a4 with ability to print longside duplex

### ISSUE THREAD

**Issue by rogerwalt** [strpeter/falshcards#2]
%Latex-code of print-version:
\documentclass[print,6paper]{kartei2}
\begin{document}

%The following code should be repeated for every flashcard: BEGIN
\cardsubject{ORDNERNAME}
\comment{falshcards,falshcards developer}
\answer{Answer}
\begin{karte}{frage}
antwort
\end{karte}
%The previous code should be repeated for every flashcard. END

\end{document}

**Comment by strpeter** [comment]
That's what you wanted me to present?

**Comment by rogerwalt** [comment]
Use this package: http://www.math.utah.edu/~jasonu/flash-cards/

**Comment by strpeter** [comment]
No, it had a reason why I chose that package... / latex-class
In my eyes, it is much nicer to handle. Or what is your motive for negotiating? The package containing flashcards.cls provides no numbering of the cards. Often, it is reasonable to have a "unique" and simple reference parameter.

**Comment by strpeter** [comment]
Just the web-interface is still remaining...
