### ISSUE TITLE
Umlaute

### ISSUE THREAD

**Issue by strpeter** [strpeter/falshcards#6]
Wieso verwendest du nicht `&auml` anstatt `ä`, `&ouml` anstatt `ö` und `&uuml` anstatt `ü`? Dies ist HTML-Code, welcher die Umlaute immer korrekt darstellt. Sonst muss man an das richtige "Encoding" denken.

**Comment by rogerwalt** [comment]
Dafür ist das Encoding im HTML als UTF-8 definiert. Spannender Link zum Thema: http://www.joelonsoftware.com/articles/Unicode.html :-)
